= Table.TransformColumnTypes(#"Promoted Headers",{{"LogFileName", type text}, {"Client", type text}, {"Url", type text}, {"HttpStatus", Int64.Type}, {"Time", type datetime}, {"RequestCount", Int64.Type}})

let
    Source = Excel.CurrentWorkbook(){[Name="IIS_Log"]}[Content],
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"LogFileName", type text}, {"Client", type text}, {"Url", type text}, {"HttpStatus", Int64.Type}, {"Time", type date}, {"RequestCount", Int64.Type}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Url", "HttpStatus", "Time"}),
    #"Grouped Rows" = Table.Group(#"Removed Other Columns", {"HttpStatus", "Url"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
    #"Sorted Rows" = Table.Sort(#"Grouped Rows",{{"HttpStatus", Order.Ascending}, {"Count", Order.Descending}})
in
    #"Sorted Rows"

