
SELECT
    ' ' '1',
    LEN(' ') [1Length],
    DATALENGTH(' ') "1DataLength",
    '  ' '2',
    LEN('  ') [2Length],
    DATALENGTH('  ') "2DataLength",
    '   ' '3',
    LEN('   ') [3Length],
    DATALENGTH('   ') "3DataLength",
    '          ' '10',
    LEN('          ') [10Length],
    DATALENGTH('          ') [10DataLength],
    LTRIM(RTRIM(' ')) TRIM_1,
    LEN(LTRIM(RTRIM(' '))) TRIM_1_Length,
    DATALENGTH(LTRIM(RTRIM(' '))) TRIM_1_DataLength,
    LTRIM(RTRIM('  ')) TRIM_2,
    LEN(LTRIM(RTRIM('  '))) TRIM_2_Length,
    DATALENGTH(LTRIM(RTRIM('  '))) TRIM_2_DataLength,
    LTRIM(RTRIM('   ')) TRIM_3,
    LEN(LTRIM(RTRIM('   '))) TRIM_3_Length,
    DATALENGTH(LTRIM(RTRIM('   '))) TRIM_3_DataLength,
    LTRIM(RTRIM('          ')) TRIM_10,
    LEN(LTRIM(RTRIM('          '))) TRIM_10_Length,
    DATALENGTH(LTRIM(RTRIM('          '))) TRIM_10_DataLength,
    NULLIF(' ', ' ') NULLIF_1,
    LEN(NULLIF(' ', ' ')) NULLIF_1_Length,
    DATALENGTH(NULLIF(' ', ' ')) NULLIF_1_DataLength,
    NULLIF('  ', ' ') NULLIF_2,
    LEN(NULLIF('  ', ' ')) NULLIF_2_Length,
    DATALENGTH(NULLIF('  ', ' ')) NULLIF_2_DataLength,
    NULLIF(LTRIM(RTRIM(' ')), ' ') NULLIF_TRIM_1,
    LEN(NULLIF(LTRIM(RTRIM(' ')), ' ')) NULLIF_TRIM_1_Length,
    DATALENGTH(NULLIF(LTRIM(RTRIM(' ')), ' ')) NULLIF_TRIM_1_DataLength,
    NULLIF(LTRIM(RTRIM('  ')), ' ') NULLIF_TRIM_2,
    LEN(NULLIF(LTRIM(RTRIM('  ')), ' ')) NULLIF_TRIM_2_Length,
    DATALENGTH(NULLIF(LTRIM(RTRIM('  ')), ' ')) NULLIF_TRIM_2_DataLength,
    NULLIF(LTRIM(RTRIM('   ')), ' ') NULLIF_TRIM_3,
    LEN(NULLIF(LTRIM(RTRIM('   ')), ' ')) NULLIF_TRIM_3_Length,
    DATALENGTH(NULLIF(LTRIM(RTRIM('   ')), ' ')) NULLIF_TRIM_3_DataLength,
    NULLIF(LTRIM(RTRIM('          ')), ' ') NULLIF_TRIM_10,
    LEN(NULLIF(LTRIM(RTRIM('          ')), ' ')) NULLIF_TRIM_10_Length,
    DATALENGTH(NULLIF(LTRIM(RTRIM('          ')), ' ')) NULLIF_TRIM_10_DataLength
