
RESTORE HEADERONLY
FROM DISK = N'D:\ScratchpadDb-08R2.bak'

RESTORE HEADERONLY
FROM DISK = N'D:\ScratchpadDb-08R2.bak'

RESTORE HEADERONLY
FROM DISK = N'D:\ScratchpadDb-12.bak'

RESTORE FILELISTONLY
FROM DISK = N'D:\ScratchpadDb-12.bak'

RESTORE FILELISTONLY
FROM DISK = N'D:\ScratchpadDb-14.bak'

RESTORE FILELISTONLY
FROM DISK = N'D:\ScratchpadDb-14.bak'
